name: Deploy to Github pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    environment: prod
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Svelte project
        run: pnpm build
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Prepare live branch
        run: |
          # Create a temporary directory for the live branch
          mkdir -p /tmp/live-branch
          cd /tmp/live-branch

          # Initialize git and set remote
          git init
          git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

          git checkout --orphan live
          git rm -rf . || true  # Clean the working directory if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy build folder to live branch
        run: |
          # Remove all files in the live branch directory (except .git)
          find /tmp/live-branch -mindepth 1 -maxdepth 1 -not -path "/tmp/live-branch/.git" -exec rm -rf {} \;

          # Copy build folder contents to live branch directory
          cp -r $GITHUB_WORKSPACE/build/* /tmp/live-branch/

      - name: Commit and push to live branch
        run: |
          cd /tmp/live-branch
          git add .
          git commit -m "Deploy: $(git rev-parse --short $GITHUB_SHA)" || echo "No changes to commit"
          git push origin HEAD:live
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
